#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        systemctl stop page-the-ripper 2>/dev/null || true
        systemctl disable page-the-ripper 2>/dev/null || true
        ;;
esac

exit 0
